# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx8G
#Modrinth
modrinth_id=BgNRHReB
modrinth_versions=["1.21.6", "1.21.7", "1.21.8"]
#CurseForge
curseforge_id=495191
#Dependencies
required_dependencies=["fabric-api", "worldweaver"]
optional_dependencies=["modmenu"]
#`release`, `beta` or `alpha`
release_channel=beta
#Loom
loom_version=1.10-SNAPSHOT
# Fabric Properties
# check these on https://fabricmc.net/versions.html
minecraft_version=1.21.8
loader_version=0.16.14
fabric_version=0.130.0+1.21.8
# Mod Properties
mod_version=21.8.1
maven_group=org.betterx
archives_base_name=bclib
# Dependencies
modmenu_version=15.0.2
//emi_version=1.1.8+1.21
wover_version=21.8.0
wunderlib_version=21.7.1